"""
Generate LaTeX table snippets from the experiment CSVs so numbers in the
paper always match the underlying data (no manual transcription).

Run from the paper/ directory (or anywhere -- paths are relative to repo
root, resolved from this file's location):

    python3 tables/make_tables.py

Outputs (overwritten each run):
    tables/main_results.tex     <- classical vs quantum, 6 scenarios
    tables/ablation1_summary.tex <- phase-1 hyperparameter ablation
    tables/ablation2_summary.tex <- phase-2 circuit-structure ablation
"""
import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = Path(__file__).resolve().parent

SCENARIO_LABELS = {
    "DE_Dir_FWD": ("Dirichlet", "Forward"),
    "DE_Dir_INV": ("Dirichlet", "Inverse"),
    "DE_Neum_FWD": ("Neumann", "Forward"),
    "DE_Neum_INV": ("Neumann", "Inverse"),
    "DE_Rob_FWD": ("Robin", "Forward"),
    "DE_Rob_INV": ("Robin", "Inverse"),
}


def fmt(x, sig=3):
    if pd.isna(x):
        return "--"
    return f"{x:.{sig}g}"


def tex_escape(s):
    """Escape LaTeX special chars in free-form strings (e.g. config names
    like 'small_init' -- the underscore otherwise triggers math-mode
    subscript parsing outside math mode and breaks compilation)."""
    return str(s).replace("_", "\\_")


def main_results_table():
    df = pd.read_csv(ROOT / "qcpinn_results/20260712_035925/results_20260712_035925.csv")
    rows = []
    for scenario, (bc, kind) in SCENARIO_LABELS.items():
        sub = df[df["scenario"] == scenario]
        c = sub[sub["model"] == "classical"].iloc[0]
        q = sub[sub["model"] == "quantum"].iloc[0]
        ratio_mae = q["mae_mean"] / c["mae_mean"]
        ratio_time = q["time_mean"] / c["time_mean"]
        rows.append(
            f"{bc} & {kind} & {fmt(c['mae_mean'])} & {fmt(q['mae_mean'])} & "
            f"{ratio_mae:.1f}$\\times$ & {fmt(c['time_mean'])} & {fmt(q['time_mean'])} & "
            f"{ratio_time:.1f}$\\times$ \\\\"
        )
    body = "\n".join(rows)
    tex = f"""% Auto-generated by tables/make_tables.py -- do not edit by hand.
\\begin{{table}}[t]
\\centering
\\caption{{Classical vs.\\ quantum PINN across six boundary-condition / problem-type
scenarios. MAE and wall-clock time (s) are means over seeds; ratio columns are
quantum relative to classical (higher = quantum worse).}}
\\label{{tab:main-results}}
\\begin{{tabular}}{{llrrrrrr}}
\\toprule
BC & Problem & MAE (cls.) & MAE (qtm.) & MAE ratio & Time (cls.) & Time (qtm.) & Time ratio \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}
\\end{{table}}
"""
    (OUT / "main_results.tex").write_text(tex)
    print("wrote", OUT / "main_results.tex")


def ablation1_table():
    df = pd.read_csv(ROOT / "qcpinn_results/ablation_20260724_020639/ablation_summary.csv")
    rows = []
    for scenario in df["scenario"].unique():
        bc, kind = SCENARIO_LABELS[scenario]
        sub = df[df["scenario"] == scenario]
        for _, r in sub.iterrows():
            rows.append(
                f"{bc} {kind} & {tex_escape(r['config'])} & {fmt(r['mae_mean'])} $\\pm$ {fmt(r['mae_std'], 2)} & "
                f"{fmt(r['time_mean'], 4)} \\\\"
            )
    body = "\n".join(rows)
    tex = f"""% Auto-generated by tables/make_tables.py -- do not edit by hand.
\\begin{{table}}[t]
\\centering
\\caption{{Phase-1 ablation: quantum-branch initialization scale and LR-schedule
floor, vs.\\ the classical reference and the untouched quantum baseline.
Neither intervention closes the accuracy or runtime gap.}}
\\label{{tab:ablation1}}
\\begin{{tabular}}{{llrr}}
\\toprule
Scenario & Config & MAE (mean $\\pm$ std) & Time (s) \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}
\\end{{table}}
"""
    (OUT / "ablation1_summary.tex").write_text(tex)
    print("wrote", OUT / "ablation1_summary.tex")


def ablation2_table():
    df = pd.read_csv(ROOT / "qcpinn_results/ablation2_20260729_225346/ablation2_summary.csv")
    rows = []
    for scenario in df["scenario"].unique():
        bc, kind = SCENARIO_LABELS[scenario]
        sub = df[df["scenario"] == scenario]
        for _, r in sub.iterrows():
            qgrad = fmt(r["qgrad_final_mean"], 3) if "qgrad_final_mean" in r and not pd.isna(r.get("qgrad_final_mean")) else "--"
            rows.append(
                f"{bc} {kind} & {tex_escape(r['config'])} & {fmt(r['mae_mean'])} $\\pm$ {fmt(r['mae_std'], 2)} & "
                f"{qgrad} & {fmt(r['time_mean'], 4)} \\\\"
            )
    body = "\n".join(rows)
    tex = f"""% Auto-generated by tables/make_tables.py -- do not edit by hand.
\\begin{{table}}[t]
\\centering
\\caption{{Phase-2 ablation: circuit width/depth sweep (narrow/baseline/wide/deep)
with final circuit-only gradient norm. Accuracy and gradient norm do not move
monotonically together, so neither a pure expressivity nor a pure
barren-plateau account fits cleanly -- see Discussion.}}
\\label{{tab:ablation2}}
\\begin{{tabular}}{{llrrr}}
\\toprule
Scenario & Config & MAE (mean $\\pm$ std) & Final $\\|\\nabla_{{\\text{{circuit}}}}\\|$ & Time (s) \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}
\\end{{table}}
"""
    (OUT / "ablation2_summary.tex").write_text(tex)
    print("wrote", OUT / "ablation2_summary.tex")


if __name__ == "__main__":
    main_results_table()
    ablation1_table()
    ablation2_table()
